### ISSUE TITLE
[1.18.2] Cycle detector doesn't show feature names

### ISSUE THREAD

**Issue by Azmalent** [alcatrazEscapee/cyanide#16]
I am a modder, and I'm trying to debug feature cycles caused by my mod. 
However, the crash log shows  `'[Unknown minecraft:worldgen/placed_feature]'` instead of actual feature names, so unfortunately it's not very helpful for my case.

```
com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 1
Feature '[Unknown minecraft:worldgen/placed_feature]'
  must be before '[Unknown minecraft:worldgen/placed_feature]' (defined in 'terraincognita:ginkgo_grove' at index 0, 1 and 6 others)
  must be before '[Unknown minecraft:worldgen/placed_feature]' (defined in 'terraincognita:boreal_forest_clearing' at index 1, 2 and 14 others)
  must be before '[Unknown minecraft:worldgen/placed_feature]' (defined in 'atmospheric:rocky_dunes' at index 1, 2 and 7 others)
```

Also I presume that instead of "step 1" it's supposed to show the actual decoration step (like UNDERGROUND_ORES, etc.)
I might be mistaken though.

**Comment by alcatrazEscapee** [comment]
> so unfortunately it's not very helpful for my case.

Given the fact it is showing you the exact biome, step, and index, it should be trivial for you to figure out the feature it is referring to, even if it cannot identify them exactly.

Additionally, given it can identify the biomes, but can't identify the features, means that this is not an error with cyanide. It cannot identify the features because these features are not registered in the runtime registry. So you have unregistered or inline features here.

> Also I presume that instead of "step 1" it's supposed to show the actual decoration step

No, because "actual decoration step" is a meaningless distinction. Step indices outside of the decoration enum used only for data generation do exist. They do not reflect any meaning present in biome data that is visible outside of a mod dev env, and so cyanide doesn't bother reporting it in that terms.

---

Finally, without any sort of reproduction case; i.e. "in a mod dev env with unknown unrelated biome mods" there's little I can do to assist you. Look at the biomes, in the step, at the index in the report - that seems like it's telling you everything it needs to, to solve the cycle.
