### ISSUE TITLE
1.16.5 Port?

### ISSUE THREAD

**Issue by Morabert** [alcatrazEscapee/cyanide#2]
A 1.16.5 Port would be Lovely & appreciated by all

**Comment by alcatrazEscapee** [comment]
Unlikely, given that I'm maintaining both 1.18 Forge + 1.18 Fabric, solely by virtue of having (nearly) identical source sets which I cannot do on 1.16.5 (due to mcp classnames, java 8, etc.). Also because the general consensus I've seen is anyone doing in depth world generation is using (predominantly) latest, or fabric.

**Comment by Morabert** [comment]
That's simply not the case. 
Even Fabric-native mods like "Better End" have their unoficcial ports doubling the fabric download count. 
A simple look at any mod with fabric/forge parity will tell the same story. e.g;
https://www.curseforge.com/members/yungnickyoung/projects
