### ISSUE TITLE
[1.21] Cyanide ignoring Enchancement's registry disabling

### ISSUE THREAD

**Issue by MoriyaShiine** [alcatrazEscapee/cyanide#31]
Loader: Fabric
Minecraft Version: 1.21.1
Cyanide Version: 5.0.0

One of Enchancement's main features is to disable loading certain enchantments, but Cyanide seems to completely overwrite that functionality (specifically [here](https://github.com/alcatrazEscapee/cyanide/blob/1.21.x/Common/src/main/java/com/alcatrazescapee/cyanide/mixin/RegistryDataLoaderMixin.java)), causing the game to not actually disable anything, and instead crash when the creative tab is opened (see [here](https://github.com/MoriyaShiine/enchancement/issues/201), isolated crash [here](https://gist.github.com/MoriyaShiine/2f5914e3565aaf5a5e0912116da39d36)). I've tried making a more generic mixin to disable enchantments, but now it errors when attempting to load the enchantments involved in enchantment providers (but presumably more), seen [here](https://gist.github.com/MoriyaShiine/ad431fe4c7a0c574880f94220dcc59f1).

What exactly is Cyanide doing to cause this, and is there anything I can do to work around it?

**Comment by alcatrazEscapee** [comment]
Very broadly, Cyanide rewrites the flow of registry resource loading in order to provide better error detection, error messages, and exception handling. It essentially _has_ to take control over this process - there is no post-facto way to provide nearly the level of depth or context that Cyanide is currently doing, by just taking vanilla's `Map<ResourceKey<?>, Exception>` and using that to extrapolate errors (for example, knowing where something was referenced, not just that an unbound holder was present in the registry). I try and call into as much vanilla logic as I can, without requiring a huge amount of brittle, difficult-to-maintain mixins into the existing vanilla code.

Looking at Enchancement, I'm assuming it's limited to [this mixin](https://github.com/MoriyaShiine/enchancement/blob/main/src/main/java/moriyashiine/enchancement/mixin/config/disabledisallowedenchantments/RegistryLoaderMixin.java), as Cyanide would be bypassing that logic completely. From a basic look,

- The first method appears to just be adding an enchantment to the registry, unconditionally. Is this not something that can be provided i.e., as all other enchantments are? By letting it be present as a resource and loading it normally?
- The second method appears to be filtering enchantments from being loaded, at the level of resource loading.

For the second injector, the options I see are:

1. Cyanide's `RegistryLoader` needs to be _completely_ rewritten, in order to invoke `RegistryDataLoader.loadContentsFromManager()`, which you currently mixin to. This involves a huge amount of work, and makes Cyanide's injections very brittle - I would need to mixin at least [one](https://github.com/alcatrazEscapee/cyanide/blob/e1b77aab6797221efb7ff8c42240ccb5d716c788/Common/src/main/java/com/alcatrazescapee/cyanide/core/RegistryLoader.java#L197-L198), [two](https://github.com/alcatrazEscapee/cyanide/blob/e1b77aab6797221efb7ff8c42240ccb5d716c788/Common/src/main/java/com/alcatrazescapee/cyanide/core/RegistryLoader.java#L207-L244), [three](https://github.com/alcatrazEscapee/cyanide/blob/e1b77aab6797221efb7ff8c42240ccb5d716c788/Common/src/main/java/com/alcatrazescapee/cyanide/core/RegistryLoader.java#L265-L277) locations, all of which would need locals access, probably thread-local or shared variable access, and potentially control flow modification. I would greatly, rather avoid this
2. You move your mixin to somewhere outside of the flow of registry loading, or at least somewhere that Cyanide doesn't take control over. For example, rather than wrapping the call to `FileToIdConverter.listMatchingResources()` within registry loading, inject into that method itself, because Cyanide still will [call it](https://github.com/alcatrazEscapee/cyanide/blob/e1b77aab6797221efb7ff8c42240ccb5d716c788/Common/src/main/java/com/alcatrazescapee/cyanide/core/RegistryLoader.java#L190)
3. Change your method of disabling these registrations from "patch the map of IDs -> Jsons" to something that hooks Fabric API's existing API for conditional registration. Cyanide [explicitly invokes it](https://github.com/alcatrazEscapee/cyanide/blob/e1b77aab6797221efb7ff8c42240ccb5d716c788/Common/src/main/java/com/alcatrazescapee/cyanide/core/RegistryLoader.java#L252), and if you moved the injection into `ResourceConditionsImpl.applyResourceConditions()` (from Fabric API), Cyanide would also catch it

**Comment by MoriyaShiine** [comment]
Thanks! Option 2 is what I'm currently looking at, I'll let you know if it works.

**Comment by MoriyaShiine** [comment]
That, along with fixing another issue related to client-server registry desyncs, managed to do it! [Here's the commit if you're curious.](https://github.com/MoriyaShiine/enchancement/commit/f054ecc36ac3c9bea7201de31833092fc3311e72)
